FROM alpine:3

LABEL author="Sintia Jamianur Jabir"
LABEL nim="11201088"
LABEL tugas="Sistem Terdistribusi"

RUN mkdir assalamualaikum
RUN echo "Assalamualaikum Sintia" > "assalamualaikum/sintia.txt"

CMD cat "assalamualaikum/sintia.txt"